language: haskell
dist: trusty

cache:
  directories:
  - $HOME/.stack
  - $TRAVIS_BUILD_DIR/.stack-work
  - $TRAVIS_BUILD_DIR/dist-newstyle

cabal: "2.4"

matrix:
  include:
    - env: BUILD=stack ARGS="--resolver lts-15.6 --system-ghc"
      ghc: "8.8.3"
      addons: {apt: {packages: [libblas-dev, liblapack-dev, g++-4.8], sources: [ubuntu-toolchain-r-test]}}

install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

script:
  - stack --no-terminal $ARGS test --haddock --no-haddock-deps
