name: pmlb
version: '0.0.0.1'
synopsis: See readme.md
description: See readme.md for description.
category: project
author: Tony Day
maintainer: tonyday567@gmail.com
copyright: Tony Day (c) 2017
license: BSD3
github: tonyday567/pmlb
extra-source-files:
- other/lhs.css
- other/header.md
- other/footer.md
default-extensions:
- NegativeLiterals
- NoImplicitPrelude
- OverloadedStrings
- UnicodeSyntax
dependencies:
- base >=4.7 && <5
library:
  source-dirs: src
  ghc-options:
  - -funbox-strict-fields
  - -fforce-recomp
  exposed-modules:
  - PMLB
  - PMLB.DataSets
  - PMLB.Csv
  - PMLB.TH
  dependencies:
  - Frames
  - QuickCheck
  - attoparsec
  - bytestring
  - data-default
  - directory
  - flow
  - foldl
  - generic-lens-labels
  - lens
  - managed
  - optparse-generic
  - pipes
  - pipes-text
  - protolude
  - streaming
  - streaming-bytestring
  - streaming-utils
  - text
  - scientific
  - distributive
  - numhask-range
  - numhask
executables:
  pmlb-app:
    main: app.hs
    source-dirs: app
    ghc-options:
    - -funbox-strict-fields
    - -fforce-recomp
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pmlb
    - QuickCheck
    - data-default
    - flow
    - formatting
    - generic-lens-labels
    - lens
    - optparse-generic
    - protolude
    - streaming
    - text
    - numhask-range
    - numhask
tests:
  test:
    main: test.hs
    source-dirs: test
    dependencies:
    - doctest
    - tasty
    - protolude
