resolver: lts-15.6

packages:
  - .

extra-deps:
  - readme-lhs-0.5.0
  - numhask-space-0.3.1
  - json-stream-0.4.2.4
  - streaming-utils-0.2.0.0
  - box-0.3.0
  - numhask-prelude-0.3.3
  - text-format-0.3.2
  - git: https://github.com/tonyday567/online-csv
    commit: 67844ac0a80d2082b805554c79bd061c2fa85750

allow-newer: true
