resolver: nightly-2018-12-15

packages:
- .

extra-deps:
  - generic-lens-labels-0.1.0.2
  - streaming-0.2.0.0
  - git: https://github.com/haskell-streaming/streaming-utils.git
    commit: 507ebc629c6b40179af5707eb337eff2fd4c3eef
  - sv-0.1
